"""Extractor plugin generator: `.agent/extractors.toml` -> `.agent/extractors/*.py`.

Brace-language plugins share one algorithm (walk top-level declarations, slice
signatures, strip bodies); only names differ per grammar (verified empirically
per language — never guessed). Unknown languages are declared by hand in the
toml; misconfigured rows are hard errors, never silent.

stdlib-only. No k3dge imports (this module must stay importable anywhere).

Known limitations of the brace-language heuristic (intentional, not yet fixed —
each requires grammar + real samples to change safely, per "never guessed" above;
this repo currently tracks zero TS/JS files, so there is no active surface):

  - body stripping cuts at the first `{`/`(`, so a *type* that embeds an object
    or function type (e.g. `Record<string, {a: number}>`, `cb: () => void`) is
    truncated; the lexical branch also decides to strip by substring sniffing
    (`"=>"` / `"function"`) instead of by node type, so `const name = "functional"`
    is mis-detected (interface text is not fully node-type driven).
  - only `tree.root_node.children` (one level) is walked: declarations wrapped in
    `declare module` / `namespace` are dropped silently (re-exports like
    `export { A, B }` are kept as their whole slice).
  - `_container_signature` filters member nodes by type but does not warn on
    `ERROR`/`MISSING` children, so a half-parsed class yields a plausible-but-short
    interface instead of a loud failure.

Adjudicated as leftover in `docs/reviews/LEFTOVERS.md` (M11); a proper fix belongs
to a milestone that installs `tree-sitter` grammars and adds golden TS samples.
"""
from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

CONFIG_REL = ".agent/extractors.toml"
PLUGDIR_REL = ".agent/extractors"
MARKER = "# GENERATED by `k3dge extractor sync`"

#: 语言名白名单：它进 `plugdir / f"{name}.py"` 当文件名，也进 `find_spec(row["grammar"])`。
#: 允许 `../`、`/`、绝对路径会把渲染出的插件写到 plugdir 之外（覆盖任意文件），畸形名还会让
#: `find_spec` 抛未捕获 ValueError。名字只该是标识符（ocr-007）。
_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_-]*$")
#: 内联进生成源码的**标识符/模块名**白名单（grammar/package/lang_func/lang_name）。
_TOKEN_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_.]*$")
#: 内联进生成源码双引号字面量的字符串**禁止**含引号/反斜杠/换行（ocr-076）。
_BAD_INLINE = re.compile(r"[\"'\\\n\r]")


def _check_name(name: object) -> str:
    n = str(name)
    if not _NAME_RE.fullmatch(n):
        raise ExtractorConfigError(
            f"invalid language name {n!r}: must match {_NAME_RE.pattern} "
            "(no path separators, '..', or leading '-')"
        )
    return n

# Verified rows only (node types confirmed by parsing samples with the real
# grammar — see task 2026-09-16-M10-feat-extractor_gen Notes). cpp/java are
# deliberately absent until someone verifies them the same way.
DEFAULT_LANGS: Dict[str, Dict[str, Any]] = {
    "typescript": {
        "grammar": "tree_sitter_typescript",
        "package": "tree-sitter-typescript",
        "lang_func": "language_typescript",
        "lang_name": "typescript",
        "suffixes": [".ts", ".tsx", ".js"],
        "wrapper": ["export_statement"],
        "wrapper_kw": "export",
        "fn": ["function_declaration", "method_definition"],
        "container": ["class_declaration"],
        "body": ["class_body"],
        "member": ["method_definition", "public_field_definition", "field_definition"],
        "type": ["interface_declaration", "type_alias_declaration", "enum_declaration"],
        "lexical_nodes": ["lexical_declaration"],
        "lexical_markers": ["=>", "function"],
        "lexical": True,
    },
    "go": {
        "grammar": "tree_sitter_go",
        "package": "tree-sitter-go",
        "lang_func": "language",
        "lang_name": "go",
        "suffixes": [".go"],
        "wrapper": [],
        "wrapper_kw": "",
        "fn": ["function_declaration", "method_declaration"],
        "container": [],
        "body": [],
        "member": [],
        # Whole-slice: type bodies hold declarations only, no logic.
        # Package vars deliberately excluded (mutable state, not contract).
        "type": ["type_declaration", "const_declaration"],
        "lexical_nodes": [],
        "lexical_markers": [],
        "lexical": False,
    },
    "rust": {
        "grammar": "tree_sitter_rust",
        "package": "tree-sitter-rust",
        "lang_func": "language",
        "lang_name": "rust",
        "suffixes": [".rs"],
        "wrapper": [],
        "wrapper_kw": "",
        "fn": ["function_item"],
        # impl/trait bodies hold functions with bodies -> walk members.
        "container": ["impl_item", "trait_item"],
        "body": ["declaration_list"],
        "member": ["function_item", "function_signature_item", "const_item", "type_item", "associated_type"],
        # Whole-slice: struct/enum/const/type bodies hold declarations only.
        # `use`/`mod` skipped (imports and nested modules are not interface).
        "type": ["struct_item", "enum_item", "const_item", "type_item"],
        "lexical_nodes": [],
        "lexical_markers": [],
        "lexical": False,
    },
    "c": {
        "grammar": "tree_sitter_c",
        "package": "tree-sitter-c",
        "lang_func": "language",
        "lang_name": "c",
        "suffixes": [".c", ".h"],
        "wrapper": [],
        "wrapper_kw": "",
        "fn": ["function_definition"],
        "container": [],
        "body": [],
        "member": [],
        # Whole-slice: typedef/struct/enum bodies hold declarations only.
        # `#include` skipped; `#define` whole-sliced (consistent with consts).
        "type": ["type_definition", "struct_specifier", "enum_specifier", "preproc_def"],
        "lexical_nodes": [],
        "lexical_markers": [],
        "lexical": False,
    },
}

_REQUIRED_KEYS = (
    "grammar", "package", "lang_func", "lang_name", "suffixes", "wrapper", "wrapper_kw",
    "fn", "container", "body", "member", "type",
    "lexical_nodes", "lexical_markers", "lexical",
)


class ExtractorConfigError(ValueError):
    """Misconfigured `.agent/extractors.toml` — loud, never silent."""


def _toml_loads(text: str) -> dict:
    try:
        import tomllib
    except ModuleNotFoundError:
        try:
            import tomli as tomllib  # type: ignore[no-redef]
        except ImportError:
            tomllib = None  # type: ignore[assignment]
    if tomllib is None:
        raise ExtractorConfigError("tomllib/tomli unavailable; cannot read .agent/extractors.toml")
    try:
        data = tomllib.loads(text)
    except Exception as exc:
        raise ExtractorConfigError(f"TOML parse failed in .agent/extractors.toml: {exc}") from exc
    if not isinstance(data, dict):
        raise ExtractorConfigError(".agent/extractors.toml must be a table")
    return data


def _check_row(name: str, row: Any) -> Dict[str, Any]:
    if not isinstance(row, dict):
        raise ExtractorConfigError(f"[languages.{name}] must be a table")
    missing = [k for k in _REQUIRED_KEYS if k not in row]
    if missing:
        raise ExtractorConfigError(f"[languages.{name}] missing keys: {', '.join(missing)}")
    extra = [k for k in row if k not in _REQUIRED_KEYS]
    if extra:
        raise ExtractorConfigError(f"[languages.{name}] unknown keys: {', '.join(extra)} (typo?)")
    for k in ("grammar", "package", "lang_func", "lang_name"):
        if not isinstance(row[k], str) or not row[k].strip():
            raise ExtractorConfigError(f"[languages.{name}] '{k}' must be a non-empty string")
    if not isinstance(row["wrapper_kw"], str):
        raise ExtractorConfigError(f"[languages.{name}] 'wrapper_kw' must be a string")
    for k in ("suffixes", "wrapper", "fn", "container", "body", "member", "type",
              "lexical_nodes", "lexical_markers"):
        v = row[k]
        if not isinstance(v, list) or not all(isinstance(x, str) for x in v):
            raise ExtractorConfigError(f"[languages.{name}] '{k}' must be a list of strings")
    # 这些值会被**直接内联**进生成的源码字面量 ⇒ 挡引号/反斜杠/换行（否则语法错或注入，ocr-076）。
    for k in ("grammar", "lang_func", "lang_name"):
        if not _TOKEN_RE.fullmatch(row[k]):
            raise ExtractorConfigError(f"[languages.{name}] '{k}' 只能是标识符/模块名（{row[k]!r}）")
    _inline = [row["package"], row["wrapper_kw"]] + [x for k in ("suffixes", "wrapper", "fn", "container",
               "body", "member", "type", "lexical_nodes", "lexical_markers") for x in row[k]]
    for v in _inline:
        if _BAD_INLINE.search(v):
            raise ExtractorConfigError(
                f"[languages.{name}] 值含引号/反斜杠/换行，不能安全内联进生成源码：{v!r}")
    if not row["suffixes"] or not all(s.startswith(".") for s in row["suffixes"]):
        raise ExtractorConfigError(f"[languages.{name}] 'suffixes' must be non-empty and dot-prefixed")
    if not isinstance(row["lexical"], bool):
        raise ExtractorConfigError(f"[languages.{name}] 'lexical' must be a boolean")
    if row["lexical"] and (not row["lexical_nodes"] or not row["lexical_markers"]):
        # lexical=true 但节点/标记为空 ⇒ 生成的插件里 `markers = " or ".join([])` 变空串 ⇒
        # `if :` 语法错（或分支恒不命中，text 未定义）——文法验证不了就得在声明面拦（ocr-244）。
        raise ExtractorConfigError(
            f"[languages.{name}] lexical=true 需要非空 lexical_nodes 与 lexical_markers")
    return dict(row)


def resolve_languages(workspace: Path) -> Dict[str, Dict[str, Any]]:
    """Merge builtin table with `.agent/extractors.toml`.

    - No toml file -> `enable` defaults to `["typescript"]` (preserve legacy behavior).
    - `enable` names resolve against builtins; unknown name without a custom row -> error.
    - `[languages.<name>]` replaces the builtin row wholesale (no per-field merge).
    - Custom rows are enabled by presence.
    Returns ordered {name: row} (enable order first, then customs).
    """
    enable: List[str] = ["typescript"]
    customs: Dict[str, Any] = {}
    cfg_path = workspace / CONFIG_REL
    if cfg_path.is_file():
        data = _toml_loads(cfg_path.read_text(encoding="utf-8"))
        raw_enable = data.get("enable", ["typescript"])
        if not isinstance(raw_enable, list) or not all(isinstance(x, str) for x in raw_enable):
            raise ExtractorConfigError("'enable' must be a list of strings")
        enable = list(raw_enable)
        raw_langs = data.get("languages", {})
        if not isinstance(raw_langs, dict):
            raise ExtractorConfigError("'languages' must be a table")
        customs = raw_langs
    resolved: Dict[str, Dict[str, Any]] = {}
    for name in enable:
        _check_name(name)
        if name in customs:
            resolved[name] = _check_row(name, customs[name])
        elif name in DEFAULT_LANGS:
            resolved[name] = dict(DEFAULT_LANGS[name])
        else:
            known = sorted(set(DEFAULT_LANGS) | set(customs))
            raise ExtractorConfigError(
                f"unknown language '{name}' in 'enable' (available: {', '.join(known)}); "
                f"define it under [languages.{name}]"
            )
    for name, row in customs.items():
        _check_name(name)
        if name not in resolved:
            resolved[name] = _check_row(name, row)
    return resolved


def _tup(items: List[str]) -> str:
    return "(" + ", ".join(f'"{x}"' for x in items) + ("," if len(items) == 1 else "") + ")"


def render_plugin(name: str, row: Dict[str, Any]) -> str:
    """Render a self-contained plugin module. Deterministic: same row -> same bytes."""
    slug = "".join(c if (c.isalnum() or c == "_") else "_" for c in name).strip("_") or "lang"
    cls = "".join(p[:1].upper() + p[1:] for p in slug.split("_") if p) + "Extractor"
    lines: List[str] = [
        MARKER + " — do not edit; `k3dge extractor sync` 会覆盖本文件。",
        f"# Source: .agent/extractors.toml + builtin table (`src/k3dge/engine/extractor_gen.py`).",
        "# 要自定义：按 `.agent/extractors/README.md`「Hand-written」另建一份（那里的规则才讲标记）。",
        f'"""{{}} interface extractor plugin (generated).'.format(name),
        "",
        "Requires the grammar package (see pip hint from `k3dge extractor sync`).",
        "Without it, matching files are silently skipped by the gate: `extract()`",
        "raises `ImportError`, which `src/k3dge/engine/contract.py` treats as a skip signal",
        "(never fatal) — see `extract_python_interface` caller's `except ImportError`.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "import threading",
        "from pathlib import Path",
        "from typing import List, Optional",
        "",
        "from k3dge.engine.contract import ContractExtractor, register_extractor",
        "",
        '_IGNORED_DIRS = {".git", ".mypy_cache", ".next", ".pytest_cache", ".venv", '
        '"__pycache__", "build", "coverage", "dist", "node_modules", "out", "vendor", "venv"}',
        '_GENERATED_MARKERS = (".generated.", ".min.")',
        '_GENERATED_SUFFIXES = (".d.ts",)',
        "_LANGUAGE = None",
        "_LANGUAGE_LOCK = threading.Lock()",
        "",
        "",
        "def _is_generated(path: Path) -> bool:",
        "    name = path.name",
        "    return any(m in name for m in _GENERATED_MARKERS) or name.endswith(_GENERATED_SUFFIXES)",
        "",
        "",
        "def _slice(source: bytes, node) -> str:",
        # "replace" 把不同非法字节序列塌成同一个 U+FFFD ⇒ 两份不同文件可产出同一接口文本（哈希
        # 碰撞面）；"backslashreplace" 保留字面转义，确定性且单射
        '    text = source[node.start_byte : node.end_byte].decode("utf-8", "backslashreplace")',
        '    return "".join(ch for ch in text if ch in "\\n\\t" or ch.isprintable()).strip()',
        "",
        "",
        "def _strip_impl_body(text: str) -> str:",
        '    """Drop the first `{ ... }` implementation body; keep signature / type members."""',
        '    brace = text.find("{")',
        "    if brace == -1:",
        "        return text.rstrip()",
        "    return text[:brace].rstrip()",
        "",
        "",
    ]
    if row["container"]:
        lines += [
            "def _container_signature(source: bytes, node) -> str:",
            "    header = _strip_impl_body(_slice(source, node))",
            "    methods: List[str] = []",
            "    for child in node.children:",
            f"        if child.type not in {_tup(row['body'])}:",
            "            continue",
            "        for member in child.children:",
            f"            if member.type in {_tup(row['member'])}:",
            "                sig = _strip_impl_body(_slice(source, member))",
            "                if sig:",
            '                    methods.append("  " + sig)',
            "    if not methods:",
            "        return header",
            '    return header + "\\n" + "\\n".join(methods)',
            "",
            "",
        ]
    # _decl_signature branches, assembled in fixed order (matches legacy _ts.py
    # branch order for the typescript row, so generated output is identical).
    search_sets = [f"{_tup(row['fn'])}", f"{_tup(row['container'])}", f"{_tup(row['type'])}"]
    if row["lexical_nodes"]:
        search_sets.append(_tup(row["lexical_nodes"]))
    branches: List[str] = []
    if row["wrapper"]:
        branches.append(
            f"    if node.type in {_tup(row['wrapper'])}:\n"
            "        inner = None\n"
            "        for child in node.children:\n"
            f"            if child.type in {' + '.join(search_sets)}:\n"
            "                inner = child\n"
            "                break\n"
            "        if inner is None:\n"
            "            return _slice(source, node)\n"
            "        return _decl_signature(source, inner, exported=True)"
        )
    if row["container"]:
        branches.append(
            f"    {'el' if branches else ''}if node.type in {_tup(row['container'])}:\n"
            "        text = _container_signature(source, node)"
        )
    branches.append(
        f"    {'el' if branches else ''}if node.type in {_tup(row['fn'])}:\n"
        "        text = _strip_impl_body(_slice(source, node))"
    )
    branches.append(
        f"    elif node.type in {_tup(row['type'])}:\n"
        "        text = _slice(source, node)"
    )
    if row["lexical"]:
        markers = " or ".join(f'"{m}" in text' for m in row["lexical_markers"])
        branches.append(
            f"    elif node.type in {_tup(row['lexical_nodes'])}:\n"
            "        if not exported:\n"
            "            return None\n"
            "        text = _slice(source, node)\n"
            f"        if {markers}:\n"
            "            text = _strip_impl_body(text)"
        )
    branches.append("    else:\n        return None")
    decl = ["def _decl_signature(source: bytes, node, exported: bool = False) -> Optional[str]:"] + branches
    if row["wrapper_kw"]:
        kw = row["wrapper_kw"]
        decl += [
            f'    if exported and not text.startswith("{kw}"):',
            f'        text = "{kw} " + text',
        ]
    decl += ["    return text", "", ""]
    lines += decl
    lines += [
        f"def _load_language():",
        '    """Construct + cache the grammar Language (immutable ⇒ shareable across threads).',
        '    A construction failure is re-raised as `ImportError` — `src/k3dge/engine/contract.py` treats that',
        '    as a skip signal, so a broken grammar never reds the whole gate (never fatal)."""',
        "    global _LANGUAGE",
        "    if _LANGUAGE is not None:",
        "        return _LANGUAGE",
        "    import importlib",
        "    try:",
        "        from tree_sitter import Language",
        f"        _grammar = importlib.import_module(\"{row['grammar']}\")",
        "    except ImportError as exc:",
        f"        raise ImportError(\"{row['package']} not installed; pip install {row['package']}\") from exc",
        "    with _LANGUAGE_LOCK:",
        "        if _LANGUAGE is None:",
        "            try:",
        f"                lang = Language(_grammar.{row['lang_func']}())",
        "            except TypeError:",
        f"                lang = Language(_grammar.{row['lang_func']}(), \"{row['lang_name']}\")  # type: ignore[call-arg]",
        "            except (ValueError, RuntimeError) as exc:",
        f"                raise ImportError(\"{row['package']} grammar unusable: \" + str(exc)) from exc",
        "            _LANGUAGE = lang",
        "    return _LANGUAGE",
        "",
        "",
        f"def extract_{slug}_interface(path: Path, include_doc: bool = False) -> str:",
        "    from tree_sitter import Parser",
        "    language = _load_language()",
        "    try:",
        "        parser = Parser(language)  # 0.21+（每次新建：Parser 非线程安全）",
        "    except TypeError:",
        "        parser = Parser()",
        "        parser.language = language  # type: ignore[attr-defined]",
        "    source = path.read_bytes()",
        "    tree = parser.parse(source)",
        "    lines = []",
        "    for node in tree.root_node.children:",
        "        text = _decl_signature(source, node)",
        "        if text:",
        "            if include_doc:",
        "                prev = node.prev_sibling",
        "                if prev is not None and prev.type == \"comment\":",
        "                    doc = _slice(source, prev).strip()",
        "                    if doc:",
        "                        text = doc + \"\\n\" + text",
        "            lines.append(text)",
        '    return "\\n".join(lines)',
        "",
        "",
        f"class {cls}(ContractExtractor):",
        "    def can_handle(self, path: Path) -> bool:",
        "        # 绝对路径/`..` 未归一就比 `parts`：`src/link/x.ts`（link→node_modules）或",
        "        # `a/../node_modules/x.ts` 都能绕过目录黑名单（判据落在未归一的形状上），故先归一再判（code-7）。",
        "        import os",
        "",
        "        if path.is_absolute() or path.suffix not in " + _tup(row["suffixes"]) + ":",
        "            return False",
        "        parts = Path(os.path.normpath(str(path))).parts",
        "        if \"..\" in parts or _IGNORED_DIRS.intersection(parts):",
        "            return False",
        "        if _is_generated(path):",
        "            return False",
        "        try:                              # 解析后仍不得越界（symlink 指向忽略目录 ⇒ 拒）",
        "            resolved = Path(os.path.realpath(str(path))).parts",
        "        except OSError:                   # pragma: no cover - 罕见 IO 故障",
        "            return False",
        "        return not _IGNORED_DIRS.intersection(resolved)",
        "",
        "    def extract(self, path: Path, include_doc: bool = False) -> str:",
        f"        return extract_{slug}_interface(path, include_doc=include_doc)",
        "",
        "",
        f"register_extractor({cls}())",
        "",
    ]
    return "\n".join(lines)


def sync_extractors(workspace: Path) -> Dict[str, Any]:
    """Render all resolved languages into `.agent/extractors/`. Idempotent.

    Writes only changed files; prunes stale GENERATED files (marker-headed `.py`
    whose stem is no longer enabled; markerless files, README and `_*.py` are
    never touched). Missing grammar packages are reported, not fatal.
    Returns {"written": [...], "pruned": [...], "missing": [(name, pip_cmd)]}.
    """
    import importlib.util

    resolved = resolve_languages(workspace)
    plugdir = workspace / PLUGDIR_REL
    plugdir.mkdir(parents=True, exist_ok=True)
    written: List[str] = []
    conflicts: List[str] = []
    for name, row in resolved.items():
        text = render_plugin(name, row)
        dest = plugdir / f"{name}.py"
        try:
            existing = dest.read_text(encoding="utf-8")
        except OSError:
            existing = None
        if existing is not None and not existing.splitlines()[0].startswith(MARKER):
            # 既有文件不是生成产物（用户手写 / 按生成头提示删了标记做定制）⇒ **不覆盖**
            # （与"markerless never pruned or overwritten"自洽，ocr-077）；改名让开是用户的事。
            conflicts.append(dest.name)
            continue
        if existing != text:
            dest.write_text(text, encoding="utf-8")
            written.append(name)
    pruned: List[str] = []
    for p in sorted(plugdir.glob("*.py")):
        if p.name.startswith("_") or p.stem in resolved:
            continue
        try:
            head = p.read_text(encoding="utf-8")[:200]
        except OSError:
            continue
        # 只看**首行**：以前 `MARKER in head`（前 200 字符子串）会把手工维护文件里
        # "提到这行标记"的注释/docstring 当成生成件直接 unlink（破坏性误判，422）
        if head[:1] and head.splitlines()[0].startswith(MARKER):
            p.unlink()
            pruned.append(p.name)
    missing: List[Tuple[str, str]] = []
    for name, row in resolved.items():
        if importlib.util.find_spec(row["grammar"]) is None:
            missing.append((name, f"pip install {row['package']}"))
    return {"written": written, "pruned": pruned, "missing": missing, "conflicts": conflicts}


def describe_extractors(workspace: Path) -> List[str]:
    """Human-readable lines for `k3dge extractor list`."""
    import importlib.util

    resolved = resolve_languages(workspace)
    plugdir = workspace / PLUGDIR_REL
    out: List[str] = []
    for name, row in sorted(resolved.items()):
        installed = importlib.util.find_spec(row["grammar"]) is not None
        present = (plugdir / f"{name}.py").is_file()
        out.append(
            f"- {name}: suffixes={','.join(row['suffixes'])} package={row['package']}"
            f"({'installed' if installed else 'NOT INSTALLED'})"
            f" plugin={'present' if present else 'missing — run `k3dge extractor sync`'}"
        )
    return out
