"""`docs/generated/{api,domains}.md` 的**纯渲染**（唯一构造处）。

归属：内容由 engine 的事实（manifest 域表 + 各域公开接口）派生 ⇒ 渲染归 engine；
写盘是 `k3dge sync` 的活（`sync.generator.render_manual_docs`）；新鲜度闸是 `evaluator` 的活
（`DOCS_GENERATED_STALE`）——**一处构造、三处消费**（写 / 比对 / 未来别的投影）。

依赖方向（ADR-0001 §2）：engine ↛ sync，故渲染必须住这里；sync 侧 import 本模块。
"""
from __future__ import annotations

import contextlib
import re
from pathlib import Path
from typing import Dict, Optional

from k3dge.engine import contract
from k3dge.engine.manifest import Manifest

def render_manual_docs_content(
    workspace: Path, manifest: Manifest, doc_cache: dict[str, str] | None = None
) -> Dict[Path, str]:
    """`docs/generated/` 的**纯渲染**（path → 应有内容；不写盘）。

    写盘 ＝ `render_manual_docs`；新鲜度闸（`evaluator`）用本函数与盘上内容比对——
    与 `doc_catalog.build_docs_index` 同形（一处构造，两处消费：写 / 比对）。
    """
    manual_dir = workspace / "docs" / "generated"
    out: Dict[Path, str] = {}

    # api.md — aggregated public interfaces per domain (docstrings included for readability)
    api_path = manual_dir / "api.md"
    lines = ["# API Reference", "", "> Auto-generated by `k3dge sync` — do not edit.", ""]
    for domain in sorted(manifest.domains):
        src = manifest.domains[domain].get("src", "")
        if not src:
            continue
        if doc_cache is not None and domain in doc_cache:
            iface = doc_cache[domain]
        else:
            iface = contract.collect_domain_interface(workspace / src, manifest, workspace, include_doc=True)
        lines.append(f"## {_head(domain)} — `{_head(src)}`")
        lines.append("")
        if iface.strip():
            # `iface` 含 docstring 首行原文（`# doc: ...`），里面出现 ``` 就会**提前关围栏**，
            # 后半截以正文渲染（投影形状坏，426）⇒ 用比内容里最长反引号串更长的围栏
            runs = max((len(m) for m in re.findall(r"`+", iface)), default=0)
            fence = "`" * max(3, runs + 1)
            lines.append(f"{fence}python")
            lines.append(iface)
            lines.append(fence)
        else:
            lines.append("_No public interface._")
        lines.append("")
    out[api_path] = "\n".join(lines)

    # domains.md — manifest snapshot (human-readable projection; NOT the consistency source of truth, which is docs/architecture/overview.md)
    arch_lines = ["# Domains Reference", "", "> Auto-generated from `.agent/manifest.json` — do not edit.", "> For cross-domain consistency rules see `docs/architecture/overview.md`.", ""]
    arch_lines.append("| Domain | Source | Spec | Description |")
    arch_lines.append("| --- | --- | --- | --- |")
    for domain in sorted(manifest.domains):
        cfg = manifest.domains[domain]
        arch_lines.append(
            f"| {_cell(domain)} | `{_cell(cfg.get('src',''))}` | `{_cell(cfg.get('spec',''))}` | {_cell(cfg.get('description',''))} |"
        )
    out[manual_dir / "domains.md"] = "\n".join(arch_lines) + "\n"
    return out


LAYOUT_START = "<!-- k3dge:layout-start -->"
LAYOUT_END = "<!-- k3dge:layout-end -->"


def _replace_between_all(content: str, start: str, end: str, replacement: str) -> Optional[str]:
    """Replace every start..end span with a single replacement (first occurrence position)."""
    if start not in content or end not in content:
        return None
    # 锚定在**第一个真有配对 end 的 start**：散文/代码围栏里引用的落单标记若在前，
    # 旧实现从它起删 ⇒ 真块被删、生成表写到示例位置，还报成功（ocr2-262）。
    s = content.find(start)
    while s != -1 and content.find(end, s + len(start)) == -1:
        s = content.find(start, s + 1)
    if s == -1:
        return None
    # remove all further duplicate spans (search from after the first start)
    while True:
        s2 = content.find(start, s + len(start))
        if s2 == -1:
            break
        e2 = content.find(end, s2)
        if e2 == -1:
            break
        content = content[:s2] + content[e2 + len(end):]
        # do not advance s; keep scanning from first marker
    e = content.find(end, s)
    if e == -1:
        return None
    e += len(end)
    return content[:s] + replacement + content[e:]


def _layout_block(manifest: Manifest) -> str:
    header = "| Domain | Source | Spec | Description |\n| --- | --- | --- | --- |"
    rows = []
    for domain in sorted(manifest.domains):
        cfg = manifest.domains[domain]
        src = cfg.get("src", "")
        spec = cfg.get("spec", "")
        desc = cfg.get("description", "")
        rows.append(f"| {_cell(domain)} | `{_cell(src)}` | `{_cell(spec)}` | {_cell(desc)} |")
    return f"{LAYOUT_START}\n{header}\n" + "\n".join(rows) + f"\n{LAYOUT_END}"


def _head(v: object) -> str:
    """api.md 标题行专用净化：`_cell`（去换行/`|`/`<>`）+ 去反引号。

    标题直接拼 `domain`/`src` 原串：含换行的域名撕开标题行、含反引号的 src
    提前闭合行内代码段 ⇒ 任意 Markdown 注入进 `docs/generated/api.md`，
    而新鲜度闸拿同一份渲染当 canonical（ocr2-261）。
    """
    return _cell(v).replace("`", "'").strip()


def _cell(v: object) -> str:
    """Markdown 表格单元转义：manifest 里的 `description`/路径是自由文本，含 `|` 会串列、含换行
    会把一行撕成两行；含 `<!--`/`-->` 会提前闭合/伪造 README 自动块标记（ocr-251/252）。
    新鲜度闸与写盘用同一份渲染结果 ⇒ 坏行会同时坏产物与坏判据。"""
    s = str(v or "").replace("\r\n", " ").replace("\n", " ").replace("\r", " ").strip()
    return s.replace("|", "\\|").replace("<", "&lt;").replace(">", "&gt;")


def render_readme_layout(workspace: Path, manifest: Manifest) -> Optional[Path]:
    """Regenerate the README layout block from the manifest (no-op if README lacks markers)."""
    import sys

    readme = workspace / "README.md"
    if not readme.exists():
        return None
    with open(readme, encoding="utf-8", newline="") as fh:   # 不做换行转换：CRLF README 不该被整文件改写成 LF（ocr-254）
        content = fh.read()
    if LAYOUT_START not in content:
        return None                                  # 没有标记 ⇒ 正常 no-op
    rendered = _replace_between_all(content, LAYOUT_START, LAYOUT_END, _layout_block(manifest))
    if rendered is None:
        # 标记不成对：与"内容已最新"是两回事，静默 None 会让脚本打 `already up to date`（ocr-253）
        print(f"[generated_docs] WARN: {readme.name} 的 layout 标记不成对 ⇒ 未刷新", file=sys.stderr)
        return None
    if rendered == content:
        return None
    tmp = readme.with_name(readme.name + ".k3dge-tmp")      # 原子替换：截断+写之间被杀不会留空 README（ocr-254）
    try:
        with open(tmp, "w", encoding="utf-8", newline="") as fh:
            fh.write(rendered)
        tmp.replace(readme)
    except OSError:
        with contextlib.suppress(OSError):
            tmp.unlink(missing_ok=True)
        raise
    return readme
