"""`docs/generated/{api,domains}.md` 的**纯渲染**（唯一构造处）。

归属：内容由 engine 的事实（manifest 域表 + 各域公开接口）派生 ⇒ 渲染归 engine；
写盘是 `k3dge sync` 的活（`sync.generator.render_manual_docs`）；新鲜度闸是 `evaluator` 的活
（`DOCS_GENERATED_STALE`）——**一处构造、三处消费**（写 / 比对 / 未来别的投影）。

依赖方向（ADR-0001 §2）：engine ↛ sync，故渲染必须住这里；sync 侧 import 本模块。
"""
from __future__ import annotations

from pathlib import Path
from typing import Dict, Optional

from k3dge.engine import contract
from k3dge.engine.manifest import Manifest

def render_manual_docs_content(
    workspace: Path, manifest: Manifest, doc_cache: dict[str, str] | None = None
) -> Dict[Path, str]:
    """`docs/generated/` 的**纯渲染**（path → 应有内容；不写盘）。

    写盘 ＝ `render_manual_docs`；新鲜度闸（`evaluator`）用本函数与盘上内容比对——
    与 `doc_catalog.build_docs_index` 同形（一处构造，两处消费：写 / 比对）。
    """
    manual_dir = workspace / "docs" / "generated"
    out: Dict[Path, str] = {}

    # api.md — aggregated public interfaces per domain (docstrings included for readability)
    api_path = manual_dir / "api.md"
    lines = ["# API Reference", "", "> Auto-generated by `k3dge sync` — do not edit.", ""]
    for domain in sorted(manifest.domains):
        src = manifest.domains[domain].get("src", "")
        if not src:
            continue
        if doc_cache is not None and domain in doc_cache:
            iface = doc_cache[domain]
        else:
            iface = contract.collect_domain_interface(workspace / src, manifest, workspace, include_doc=True)
        lines.append(f"## {domain} — `{src}`")
        lines.append("")
        if iface.strip():
            lines.append("```python")
            lines.append(iface)
            lines.append("```")
        else:
            lines.append("_No public interface._")
        lines.append("")
    out[api_path] = "\n".join(lines)

    # domains.md — manifest snapshot (human-readable projection; NOT the consistency source of truth, which is docs/architecture/overview.md)
    arch_lines = ["# Domains Reference", "", "> Auto-generated from `.agent/manifest.json` — do not edit.", "> For cross-domain consistency rules see `docs/architecture/overview.md`.", ""]
    arch_lines.append("| Domain | Source | Spec | Description |")
    arch_lines.append("| --- | --- | --- | --- |")
    for domain in sorted(manifest.domains):
        cfg = manifest.domains[domain]
        arch_lines.append(
            f"| {domain} | `{cfg.get('src','')}` | `{cfg.get('spec','')}` | {cfg.get('description','')} |"
        )
    out[manual_dir / "domains.md"] = "\n".join(arch_lines) + "\n"
    return out
