# GENERATED by `k3dge extractor sync` — do not edit.
# Source: .agent/extractors.toml + builtin table (`src/k3dge/engine/extractor_gen.py`).
# To customize: copy this file to a new name, remove this header
# (markerless files are never pruned or overwritten), and edit freely.
"""typescript interface extractor plugin (generated).

Requires the grammar package (see pip hint from `k3dge extractor sync`).
Without it, matching files are silently skipped by the gate: `extract()`
raises `ImportError`, which `engine/contract.py` treats as a skip signal
(never fatal) — see `extract_python_interface` caller's `except ImportError`.
"""

from __future__ import annotations

from pathlib import Path
from typing import List, Optional

from k3dge.engine.contract import ContractExtractor, register_extractor

_IGNORED_DIRS = {".git", ".mypy_cache", ".next", ".pytest_cache", ".venv", "__pycache__", "build", "coverage", "dist", "node_modules", "out", "vendor", "venv"}
_GENERATED_MARKERS = (".generated.", ".min.")
_GENERATED_SUFFIXES = (".d.ts",)
_PARSER = None


def _is_generated(path: Path) -> bool:
    name = path.name
    return any(m in name for m in _GENERATED_MARKERS) or name.endswith(_GENERATED_SUFFIXES)


def _slice(source: bytes, node) -> str:
    text = source[node.start_byte : node.end_byte].decode("utf-8", "replace")
    return "".join(ch for ch in text if ch in "\n\t" or ch.isprintable()).strip()


def _strip_impl_body(text: str) -> str:
    """Drop the first `{ ... }` implementation body; keep signature / type members."""
    brace = text.find("{")
    if brace == -1:
        return text.rstrip()
    return text[:brace].rstrip()


def _container_signature(source: bytes, node) -> str:
    header = _strip_impl_body(_slice(source, node))
    methods: List[str] = []
    for child in node.children:
        if child.type not in ("class_body",):
            continue
        for member in child.children:
            if member.type in ("method_definition", "public_field_definition", "field_definition"):
                sig = _strip_impl_body(_slice(source, member))
                if sig:
                    methods.append("  " + sig)
    if not methods:
        return header
    return header + "\n" + "\n".join(methods)


def _decl_signature(source: bytes, node, exported: bool = False) -> Optional[str]:
    if node.type in ("export_statement",):
        inner = None
        for child in node.children:
            if child.type in ("function_declaration", "method_definition") + ("class_declaration",) + ("interface_declaration", "type_alias_declaration", "enum_declaration") + ("lexical_declaration",):
                inner = child
                break
        if inner is None:
            return _slice(source, node)
        return _decl_signature(source, inner, exported=True)
    elif node.type in ("class_declaration",):
        text = _container_signature(source, node)
    elif node.type in ("function_declaration", "method_definition"):
        text = _strip_impl_body(_slice(source, node))
    elif node.type in ("interface_declaration", "type_alias_declaration", "enum_declaration"):
        text = _slice(source, node)
    elif node.type in ("lexical_declaration",):
        if not exported:
            return None
        text = _slice(source, node)
        if "=>" in text or "function" in text:
            text = _strip_impl_body(text)
    else:
        return None
    if exported and not text.startswith("export"):
        text = "export " + text
    return text


def extract_typescript_interface(path: Path) -> str:
    global _PARSER
    try:
        from tree_sitter import Language, Parser
        import importlib
        _grammar = importlib.import_module("tree_sitter_typescript")
    except ImportError as exc:
        raise ImportError("tree-sitter-typescript not installed; pip install tree-sitter-typescript") from exc
    if _PARSER is None:
        try:
            language = Language(_grammar.language_typescript())
        except TypeError:
            language = Language(_grammar.language_typescript(), "typescript")  # type: ignore[call-arg]
        try:
            parser = Parser(language)  # 0.21+
        except TypeError:
            parser = Parser()
            parser.language = language  # type: ignore[attr-defined]
        _PARSER = parser
    parser = _PARSER
    source = path.read_bytes()
    tree = parser.parse(source)
    lines = []
    for node in tree.root_node.children:
        text = _decl_signature(source, node)
        if text:
            lines.append(text)
    return "\n".join(lines)


class TypescriptExtractor(ContractExtractor):
    def can_handle(self, path: Path) -> bool:
        return (path.suffix in (".ts", ".tsx", ".js") and not _IGNORED_DIRS.intersection(path.parts) and not _is_generated(path))

    def extract(self, path: Path, include_doc: bool = False) -> str:
        return extract_typescript_interface(path)


register_extractor(TypescriptExtractor())
