# GENERATED by `k3dge extractor sync` — do not edit; `k3dge extractor sync` 会覆盖本文件。
# Source: .agent/extractors.toml + builtin table (`src/k3dge/engine/extractor_gen.py`).
# 要自定义：按 `.agent/extractors/README.md`「Hand-written」另建一份（那里的规则才讲标记）。
"""typescript interface extractor plugin (generated).

Requires the grammar package (see pip hint from `k3dge extractor sync`).
Without it, matching files are silently skipped by the gate: `extract()`
raises `ImportError`, which `engine/contract.py` treats as a skip signal
(never fatal) — see `extract_python_interface` caller's `except ImportError`.
"""

from __future__ import annotations

import threading
from pathlib import Path
from typing import List, Optional

from k3dge.engine.contract import ContractExtractor, register_extractor

_IGNORED_DIRS = {".git", ".mypy_cache", ".next", ".pytest_cache", ".venv", "__pycache__", "build", "coverage", "dist", "node_modules", "out", "vendor", "venv"}
_GENERATED_MARKERS = (".generated.", ".min.")
_GENERATED_SUFFIXES = (".d.ts",)
_LANGUAGE = None
_LANGUAGE_LOCK = threading.Lock()


def _is_generated(path: Path) -> bool:
    name = path.name
    return any(m in name for m in _GENERATED_MARKERS) or name.endswith(_GENERATED_SUFFIXES)


def _slice(source: bytes, node) -> str:
    text = source[node.start_byte : node.end_byte].decode("utf-8", "backslashreplace")
    return "".join(ch for ch in text if ch in "\n\t" or ch.isprintable()).strip()


def _strip_impl_body(text: str) -> str:
    """Drop the first `{ ... }` implementation body; keep signature / type members."""
    brace = text.find("{")
    if brace == -1:
        return text.rstrip()
    return text[:brace].rstrip()


def _container_signature(source: bytes, node) -> str:
    header = _strip_impl_body(_slice(source, node))
    methods: List[str] = []
    for child in node.children:
        if child.type not in ("class_body",):
            continue
        for member in child.children:
            if member.type in ("method_definition", "public_field_definition", "field_definition"):
                sig = _strip_impl_body(_slice(source, member))
                if sig:
                    methods.append("  " + sig)
    if not methods:
        return header
    return header + "\n" + "\n".join(methods)


def _decl_signature(source: bytes, node, exported: bool = False) -> Optional[str]:
    if node.type in ("export_statement",):
        inner = None
        for child in node.children:
            if child.type in ("function_declaration", "method_definition") + ("class_declaration",) + ("interface_declaration", "type_alias_declaration", "enum_declaration") + ("lexical_declaration",):
                inner = child
                break
        if inner is None:
            return _slice(source, node)
        return _decl_signature(source, inner, exported=True)
    elif node.type in ("class_declaration",):
        text = _container_signature(source, node)
    elif node.type in ("function_declaration", "method_definition"):
        text = _strip_impl_body(_slice(source, node))
    elif node.type in ("interface_declaration", "type_alias_declaration", "enum_declaration"):
        text = _slice(source, node)
    elif node.type in ("lexical_declaration",):
        if not exported:
            return None
        text = _slice(source, node)
        if "=>" in text or "function" in text:
            text = _strip_impl_body(text)
    else:
        return None
    if exported and not text.startswith("export"):
        text = "export " + text
    return text


def _load_language():
    """Construct + cache the grammar Language (immutable ⇒ shareable across threads).
    A construction failure is re-raised as `ImportError` — `engine/contract.py` treats that
    as a skip signal, so a broken grammar never reds the whole gate (never fatal)."""
    global _LANGUAGE
    if _LANGUAGE is not None:
        return _LANGUAGE
    import importlib
    try:
        from tree_sitter import Language
        _grammar = importlib.import_module("tree_sitter_typescript")
    except ImportError as exc:
        raise ImportError("tree-sitter-typescript not installed; pip install tree-sitter-typescript") from exc
    with _LANGUAGE_LOCK:
        if _LANGUAGE is None:
            try:
                lang = Language(_grammar.language_typescript())
            except TypeError:
                lang = Language(_grammar.language_typescript(), "typescript")  # type: ignore[call-arg]
            except (ValueError, RuntimeError) as exc:
                raise ImportError("tree-sitter-typescript grammar unusable: " + str(exc)) from exc
            _LANGUAGE = lang
    return _LANGUAGE


def extract_typescript_interface(path: Path, include_doc: bool = False) -> str:
    from tree_sitter import Parser
    language = _load_language()
    try:
        parser = Parser(language)  # 0.21+（每次新建：Parser 非线程安全）
    except TypeError:
        parser = Parser()
        parser.language = language  # type: ignore[attr-defined]
    source = path.read_bytes()
    tree = parser.parse(source)
    lines = []
    for node in tree.root_node.children:
        text = _decl_signature(source, node)
        if text:
            if include_doc:
                prev = node.prev_sibling
                if prev is not None and prev.type == "comment":
                    doc = _slice(source, prev).strip()
                    if doc:
                        text = doc + "\n" + text
            lines.append(text)
    return "\n".join(lines)


class TypescriptExtractor(ContractExtractor):
    def can_handle(self, path: Path) -> bool:
        # 绝对路径/`..` 未归一就比 `parts`：`src/link/x.ts`（link→node_modules）或
        # `a/../node_modules/x.ts` 都能绕过目录黑名单（判据落在未归一的形状上），故先归一再判（code-7）。
        import os

        if path.is_absolute() or path.suffix not in (".ts", ".tsx", ".js"):
            return False
        parts = Path(os.path.normpath(str(path))).parts
        if ".." in parts or _IGNORED_DIRS.intersection(parts):
            return False
        if _is_generated(path):
            return False
        try:                              # 解析后仍不得越界（symlink 指向忽略目录 ⇒ 拒）
            resolved = Path(os.path.realpath(str(path))).parts
        except OSError:                   # pragma: no cover - 罕见 IO 故障
            return False
        return not _IGNORED_DIRS.intersection(resolved)

    def extract(self, path: Path, include_doc: bool = False) -> str:
        return extract_typescript_interface(path, include_doc=include_doc)


register_extractor(TypescriptExtractor())
